### ISSUE TITLE
Add code formatter📝

### ISSUE THREAD

**Issue by therealtoresto** [AlinaSyniavska/makeup-shop-fe#1]
Hello👋🏻, your projects are awesome, but for making your code more quality, please try to use code formatter or analyzer, for example [ESlint](https://eslint.org/) or [Prettier](https://prettier.io/).
For example this line https://github.com/AlinaSyniavska/makeup-shop-fe/blob/5f7d92029937709f117e31f04288dde1ce4d11e7/src/App.tsx#L1 can be more readable if add spaces within **figured brackets** like this:
```js
import { FC } from "react"; 
```
Happy Coding!

**Comment by AlinaSyniavska** [comment]
Thank you for your advice.

пт, 17 февр. 2023 г. в 16:12, Taras Bondaruk ***@***.***>:
